# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcafeapp', '0038_ordertrackingtable_sub_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bf_fruits_grains_menu',
            old_name='bf_fg_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='bf_fruits_grains_menu',
            old_name='fg_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='bf_morning_meals',
            old_name='bf_mm_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='bf_morning_meals',
            old_name='mm_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='bf_organic_eggs',
            old_name='bf_oe_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='bf_organic_eggs',
            old_name='oe_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='bf_sandwitches',
            old_name='bf_sd_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='bf_sandwitches',
            old_name='sd_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='bf_sides',
            old_name='bf_sd_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='bf_sides',
            old_name='sd_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='bf_sweets',
            old_name='bf_sw_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='bf_sweets',
            old_name='sw_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='kids_breakfast',
            old_name='km_bf_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='kids_breakfast',
            old_name='bf_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='kids_mains',
            old_name='km_main_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='kids_mains',
            old_name='main_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='lm_salads',
            old_name='lm_sd_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='lm_salads',
            old_name='sd_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='lm_sandwitches_burgers',
            old_name='lm_sb_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='lm_sandwitches_burgers',
            old_name='sb_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='lm_shareables',
            old_name='lm_sh_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='lm_shareables',
            old_name='sh_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='mains_grills_fromgrill',
            old_name='mg_fg_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='mains_grills_fromgrill',
            old_name='fg_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='mains_grills_mains',
            old_name='mg_m_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='mains_grills_mains',
            old_name='main_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='mains_grills_sides',
            old_name='mg_sd_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='mains_grills_sides',
            old_name='sd_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='ssj_bottled_juices',
            old_name='bot_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='ssj_bottled_juices',
            old_name='bot_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='ssj_fresh_juices',
            old_name='fj_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='ssj_fresh_juices',
            old_name='fj_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='ssj_milkshakes',
            old_name='ms_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='ssj_milkshakes',
            old_name='ms_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='ssj_smoothies',
            old_name='smoothie_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='ssj_smoothies',
            old_name='smoothie_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='ssj_sparklers',
            old_name='sk_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='ssj_sparklers',
            old_name='sk_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='tea_coffees_cold_coffee',
            old_name='cc_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='tea_coffees_cold_coffee',
            old_name='cc_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='tea_coffees_hot_coffee',
            old_name='hc_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='tea_coffees_hot_coffee',
            old_name='hc_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='tea_coffees_tea',
            old_name='tea_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='tea_coffees_tea',
            old_name='tea_name',
            new_name='item_name',
        ),
    ]
