from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('pcafeapp.views',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','HomePage'),
    url(r'^register$','UserRegister'),
    url(r'^success$','SuccessMessage'),
    url(r'^login$','UserLogin'),
    url(r'^myprofile$','UserProfile'),
    url(r'^address$','ShowAddress'),
    url(r'^addnew$','AddNewAddress'),
    url(r'^editaddress$','EditAddress'),
    url(r'^deleteaddress$','DeleteAddress'),
    url(r'^logout$','Logout'),
    url(r'^forgotpwd$','ForgotPwd'),
    url(r'^sentpwd$','SentPwd'),
    url(r'^feedback$','UserFeedBack'),    
    url(r'^guestsuccess$','GuestSuccess'), 
    url(r'^contactus$','UserContactUs'),
    url(r'^orderitem$','OrderItem'), 
    url(r'^deleteorder$','DeleteOrder'), 
    url(r'^checkout$','Checkout'), 
    url(r'^howtoorder$','HowToOrder'), 
    url(r'^consucces$','ContactSuccess'), 
    url(r'^confirmorder$','ConfirmOrder'), 
    url(r'^clear$','ClearOrder'), 
    url(r'^orderhistory$','OrderHistory'),
    url(r'^order_details','OrderDetails'),
    url(r'^checkoutaddnew$','CheckoutAddNewAddress'),
    url(r'^verify$','UserVerification'),
    url(r'^userverified$','UserVerified'),
    url(r'^changeitem$','ChangeItem'),
    url(r'^addrequest$','AddRequest'),
   
)
